version: '3'

services:
  aplicacao:
    container_name: "dev-hiring-challenge"
    build: .
    ports:
      - "8000:8000"
    networks:
      - "postgres"
  postgres:
    container_name: "postgres"
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "teste"
    ports:
      - "5432:5432"
    networks:
      - "postgres"
    volumes:
      - "./data:/var/lib/postgresql/data"

networks:
  postgres:
    driver: bridge